# UI
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = ['DeinUpdate']


[[plugins]]
repo = 'tpope/vim-rhubarb'
on_source = ['vim-fugitive']

[[plugins]]
repo = 'kassio/neoterm'
on_cmd = ['Tnew', 'Ttoggle']
hook_add = '''
let g:neoterm_autoinsert = 0
let g:neoterm_autojump = 1
let g:neoterm_autoscroll = 1
let g:neoterm_default_mod = "botright"
'''

[[plugins]]
repo = 'shime/vim-livedown'
on_ft = ['markdown']
