# Dein
[[plugins]]
repo = 'Shougo/dein.vim'

# Utilitys
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

# 補完
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Filer
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons'] 
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# UI
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['lightline-hybrid.vim', 'tmuxline.vim']
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.lua
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'edkolev/tmuxline.vim'
hook_add = '''
source ~/.config/nvim/plugins/tmuxline.rc.lua
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'unblevable/quick-scope'
hook_add = '''
let g:qs_highlight_on_keys = ['f', 'F']
augroup qs_colors
  autocmd!
  autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
  autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
augroup END
'''

