# UI
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_event = 'CmdlineEnter'

# Git
[[plugins]] 
repo = 'tpope/vim-fugitive'
on_event = 'CmdlineEnter'
depends = ['vim-rhubarb']


[[plugins]]
repo = 'tpope/vim-rhubarb'
on_event = 'CmdlineEnter'
on_source = ['vim-fugitive']

[[plugins]]
repo = 'kassio/neoterm'
on_event = ['CmdUndefined']
hook_add = '''
let g:neoterm_autoinsert = 0
let g:neoterm_autojump = 1
let g:neoterm_autoscroll = 1
let g:neoterm_default_mod = "botright"
'''

[[plugins]]
repo = 'shime/vim-livedown'
on_ft = ['markdown']

# Auto pairs
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'InsertEnter'

# Auto save
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
on_event = 'InsertEnter'
hook_add = '''
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = 'voldikss/vim-translator'
on_event = 'CmdlineEnter'
hook_add = '''
let g:translator_target_lang = 'ja'
let g:translator_default_engines = ['google']
'''

