# Dein
[[plugins]]
repo = 'Shougo/dein.vim'

# Utilitys
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# Git
[[plugins]] 
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# Filer
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons'] 
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'
on_source = ['defx.nvim']

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = ['defx.nvim']

# UI
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['lightline-hybrid.vim', 'tmuxline.vim']
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'
on_source = ['lightline.vim']

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'edkolev/tmuxline.vim'
hook_add = '''
source ~/.config/nvim/plugins/tmuxline.rc.vim
'''

[[plugins]]
repo = 'voldikss/vim-translator'
hook_add = '''
let g:translator_target_lang = 'ja'
let g:translator_default_engines = ['google']
'''

[[plugins]]
repo = 'tpope/vim-surround'
