{ config, lib, pkgs, ... }:

##############################################################################
# llama.cpp (PrismML フォーク) を llama-swap の後ろに並べたローカル LLM ルーター。
# OpenAI 互換 API を 127.0.0.1:8888 で待ち受けます (8080 は Open WebUI)。
#
# ドキュメント (経緯・実測値・呼び出し側の注意はコメントではなくこちら):
#   docs/services/llama-cpp.md    概要、モデル一覧、呼び出し側の注意
#   docs/gpu-vram-budget.md       GPU の対応表と VRAM の実測内訳
#   docs/runbooks/llama-cpp.md    フォーク更新、GPU 載せ替えなどの手順
#   docs/decisions/2026-09-2*-*   ビルド方式、llama-swap/matrix、Laya、ollama からの移行
#
# ここを変えたら、上の docs の該当箇所も同じコミットで直すこと。
##############################################################################

let
  m = import ../machine.nix;

  port = 8888;

  # モデルとルーターの作業ディレクトリ。bonsai-workspaces のチェックアウト。
  # モデルを disko のデータセットに置かない理由は docs/services/llama-cpp.md。
  workDir = "/home/${m.userName}/bonsai-workspaces";
  modelsDir = "${workDir}/models";

  ##########################################################################
  # Laya (PyTorch の決定モデル) — llama.cpp ではないが、1660 SUPER の VRAM を
  # matrix で一元管理するためにここに同居させています。pip venv で動かす理由も含め
  # docs/decisions/2026-09-23-laya-in-llama-swap.md。
  ##########################################################################
  layaDir = "${workDir}/laya";
  layaVenv = "${layaDir}/venv";
  layaHfHome = "${layaDir}/hf";
  layaRepo = "convaiinnovations/laya";
  layaSubfolder = "multilingual"; # 322M, mmBERT-base, 1024 ctx。日本語のため

  # 実測で動いた組み合わせに固定 (2026-09-23)。torch は cu121 wheel。
  layaTorchVersion = "2.5.1";
  layaVersion = "0.3.6";

  # pip の torch wheel を NixOS で動かすのに要る 3 つ: libstdc++ (stdenv.cc.cc)、
  # zlib、libcuda.so の在処 /run/opengl-driver/lib (どれが欠けても動かない、実測)。
  layaLdPath = lib.makeLibraryPath [ pkgs.stdenv.cc.cc pkgs.zlib ] + ":/run/opengl-driver/lib";

  # Laya の HTTP ラッパー (標準ライブラリのみ)。
  # ★ ロード順「CPU でロード → half() → GPU」は変えないこと ★ fp32 のまま GPU に
  #   載せた時点で 1660 SUPER が OOM します (実測は docs の Laya の判断記録)。
  layaServer = pkgs.writeText "laya-server.py" ''
    """Minimal HTTP wrapper around the laya decision model, for llama-swap.

    Generated by modules/llama-cpp.nix -- do not edit in place.

    Endpoints:
      GET  /health   -> 200 once the model is loaded (llama-swap checkEndpoint)
      POST /decide   -> {"state": ..., "questions": {...}} -> laya's answer
    """
    import argparse
    import json
    import sys
    import traceback
    from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

    import torch
    import laya

    REPO = "${layaRepo}"
    SUBFOLDER = "${layaSubfolder}"

    agent = None


    def load_agent():
        """Load on CPU, cast to fp16, then move to the GPU.

        The order matters: the fp32 weights (~1.3 GiB) do not fit next to the
        embedding server on the 1660 SUPER, so they must never touch the card.
        """
        global agent
        a = laya.load(REPO, subfolder=SUBFOLDER, device="cpu")
        if torch.cuda.is_available():
            a.model.half()
            a.model.to("cuda").eval()
            a.device = torch.device("cuda")
            a.dtype = torch.float16
            torch.cuda.empty_cache()
            print(
                "[laya-server] loaded fp16 on %s" % torch.cuda.get_device_name(0),
                flush=True,
            )
        else:
            # Keep serving rather than dying: a slower answer beats a dead
            # branch in n8n. ~112 ms vs ~71 ms for a short input (measured).
            print(
                "[laya-server] WARNING: CUDA unavailable, running on CPU (slower)",
                flush=True,
            )
        agent = a


    class Handler(BaseHTTPRequestHandler):
        def _send(self, code, payload):
            body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            if self.path.rstrip("/") in ("/health", ""):
                ready = agent is not None
                self._send(200 if ready else 503, {"status": "ok" if ready else "loading"})
            else:
                self._send(404, {"error": "not found: %s" % self.path})

        def do_POST(self):
            if self.path.rstrip("/") != "/decide":
                self._send(404, {"error": "not found: %s" % self.path})
                return
            try:
                n = int(self.headers.get("Content-Length") or 0)
                req = json.loads(self.rfile.read(n) or b"{}")
                state = req["state"]
                questions = req["questions"]
            except Exception as e:
                self._send(400, {"error": "bad request: %s" % e})
                return
            try:
                self._send(200, agent.system_one(state, questions))
            except Exception as e:
                traceback.print_exc()
                self._send(500, {"error": str(e)})

        def log_message(self, fmt, *args):
            # journald already timestamps; keep one line per request.
            sys.stderr.write("[laya-server] " + (fmt % args) + "\n")


    def main():
        ap = argparse.ArgumentParser()
        ap.add_argument("--port", type=int, required=True)
        ap.add_argument("--host", default="127.0.0.1")
        args = ap.parse_args()

        load_agent()
        srv = ThreadingHTTPServer((args.host, args.port), Handler)
        print("[laya-server] listening on %s:%d" % (args.host, args.port), flush=True)
        srv.serve_forever()


    if __name__ == "__main__":
        main()
  '';

  ##########################################################################
  # PrismML フォークのソース。rev / hash は ~/bonsai-workspaces/flake.lock と
  # 同一で、正は向こう側です (更新手順は docs/runbooks/llama-cpp.md)。
  # フォークを使う理由と、flake input にしない理由は
  # docs/decisions/2026-09-21-llama-cpp-prism-build.md。
  ##########################################################################
  prismRev = "9a9394a895b96003ca842a6041cb28ac49a108f7";
  prismHash = "sha256-KDecY+v9S/193mLGse5EsJPugZR1wxWzOlOU7GuMd5Y=";

  prismSrc = pkgs.fetchFromGitHub {
    owner = "PrismML-Eng";
    repo = "llama.cpp";
    rev = prismRev;
    hash = prismHash;
  };

  # nixpkgs の llama-cpp をフォークのソースで差し替える。cudaSupport は
  # nixpkgs 全体ではなくここで名指し (CLAUDE.md の cudaSupport の項)。
  # patches = [] は、nixpkgs 側のパッチが本家の行番号前提でフォークに当たらないため。
  llamaCppPrism =
    (pkgs.unstable.llama-cpp.override { cudaSupport = true; }).overrideAttrs
      (old: {
        pname = "llama-cpp-prism";
        version = builtins.substring 0 7 prismRev;
        src = prismSrc;
        patches = [ ];
        doCheck = false;

        # このホストの 2 枚だけ: 75 = GTX 1660 SUPER / 86 = RTX 3060 Ti。
        # nixpkgs 既定の 9 アーキテクチャ分だと初回ビルドが数倍かかります。
        # ★ GPU を載せ替えたら更新すること ★ 合わない SM では起動時に CUDA エラー。
        cmakeFlags =
          (builtins.filter
            (f: !(lib.hasPrefix "-DCMAKE_CUDA_ARCHITECTURES" f))
            old.cmakeFlags)
          ++ [ "-DCMAKE_CUDA_ARCHITECTURES:STRING=75;86" ];
      });

  ##########################################################################
  # llama-swap の設定 YAML。モデルごとに llama-server を子プロセスで起動し、
  # 同居できる組み合わせを matrix の sets で書きます
  # (フォーク自身のルーターを使わない理由は
  #  docs/decisions/2026-09-22-llama-swap-matrix.md)。
  #
  # GPU はモデルごとの CUDA_VISIBLE_DEVICES で割り当てます。番号は PCI バス順:
  #   "1" = RTX 3060 Ti (bonsai 系)   "0" = GTX 1660 SUPER (embedding / laya)
  # 数値 (context 上限、VRAM 内訳) はすべて実測で、docs/gpu-vram-budget.md に
  # あります。★ 実測せずに数値を上げないこと ★
  ##########################################################################
  bonsaiModel = "${modelsDir}/Ternary-Bonsai-2-27B-gguf/Ternary-Bonsai-2-27B-PTQ1_0.gguf";

  swapConfig = pkgs.writeText "llama-swap.yaml" ''
    # このファイルは Nix が生成しています。直接編集しないこと
    # (modules/llama-cpp.nix が正)。

    # 子プロセスの llama-server が使うポートの開始番号。8888 (llama-swap 本体)
    # や 8080 (Open WebUI)、5678 (n8n) と衝突しない帯を選んでいます。
    startPort: 18900

    # 27B のロードには時間がかかります。既定の 500 秒で足りていますが、
    # 明示しておきます。
    healthCheckTimeout: 500
    logLevel: info

    # 0 = 自動アンロードしない。追い出しは matrix に任せます。
    globalTTL: 0

    macros:
      # PORT は llama-swap がモデルごとに割り当てる変数で、Nix の補間ではありません
      # (二重シングルクォートでエスケープしています)。
      "server": "${llamaCppPrism}/bin/llama-server --port ''${PORT}"

    models:
      # Bonsai 2 / PTQ1_0 を 3060 Ti 単体で。
      # -c 81920 は KV q4_0 での実測上限 (90112 は NG)。上げないこと。
      # -np 1 は消さないこと (既定の 4 スロットだと 27B が OOM する)。
      "bonsai":
        name: "Bonsai 2 27B (80K)"
        env:
          - "CUDA_VISIBLE_DEVICES=1"
        cmd: |
          ''${server}
          --model ${bonsaiModel}
          --jinja
          -np 1
          -ngl 99
          -c 81920
          --cache-type-k q4_0
          --cache-type-v q4_0
          --temp 0.5
          --top-p 0.85
          --top-k 20

      # 同じ重み + vision projector (+600 MB)。その分 context が 8192 に落ちます。
      "bonsai-vision":
        name: "Bonsai 2 27B (vision)"
        env:
          - "CUDA_VISIBLE_DEVICES=1"
        cmd: |
          ''${server}
          --model ${bonsaiModel}
          --mmproj ${modelsDir}/Ternary-Bonsai-2-27B-gguf/Ternary-Bonsai-2-27B-mmproj-Q8_0.gguf
          --jinja
          -np 1
          -ngl 99
          -c 8192
          --cache-type-k q8_0
          --cache-type-v q8_0
          --temp 0.5
          --top-p 0.85
          --top-k 20

      # ここから下は 1660 SUPER。CUDA_VISIBLE_DEVICES=0 で 3060 Ti をカードごと
      # 見せないことが、bonsai と干渉しないことの実体です (-ngl だけでは足りない)。
      # このカードの空きは数百 MiB しかありません。足す前に必ず実測すること。

      # Qwen3-Embedding-4B、2560 次元 (実機のルーターで測定済み)。OpenViking 用。
      "embedding":
        name: "Qwen3 Embedding 4B"
        env:
          - "CUDA_VISIBLE_DEVICES=0"
        cmd: |
          ''${server}
          --model ${modelsDir}/Qwen3-Embedding-4B-GGUF/Qwen3-Embedding-4B-Q4_K_M.gguf
          --embeddings
          --pooling last
          -ngl 99
          -c 8192

      # Laya multilingual (322M) — n8n のフロー分岐用の決定モデル (PyTorch)。
      # 呼び出しは POST /upstream/laya/decide (docs/services/llama-cpp.md)。
      # concurrencyLimit 1: GPU 上のモデルは 1 つで、並列にしても VRAM の山が
      # 高くなるだけなので直列化します。
      "laya":
        name: "Laya multilingual (decision)"
        checkEndpoint: /health
        concurrencyLimit: 1
        env:
          - "CUDA_VISIBLE_DEVICES=0"
          - "LD_LIBRARY_PATH=${layaLdPath}"
          - "HF_HOME=${layaHfHome}"
          # 実行時にネットワークへ出させない。重みは laya-setup.service が
          # 事前に取得しています。取り損ねていればここで即座に失敗します。
          - "HF_HUB_OFFLINE=1"
        cmd: |
          ${layaVenv}/bin/python ${layaServer} --port ''${PORT}

    # 同時に走ってよい組み合わせ。set の部分集合も許可されるので 1 本で足ります。
    # bonsai と bonsai-vision は同じ 3060 Ti を占有するため別の枝です。
    routing:
      router:
        use: matrix
        settings:
          matrix:
            evict_costs:
              # 27B + 80K の KV。ロードが重いので最後まで残す。
              bonsai: 50
              bonsai-vision: 50
              # 埋め込みは軽く、別のカードなので追い出す理由が無い。
              embedding: 1
              # n8n の分岐を同期で待たせるので埋め込みより残す。bonsai よりは安い。
              laya: 30
            sets:
              generation: "(bonsai | bonsai-vision) & embedding & laya"
  '';
in
{
  # environment.systemPackages にはあえて入れていません。`llama` という一般的
  # すぎる名前のバイナリを含み、PATH で衝突しうるためです。対話的に使う方法は
  # docs/services/llama-cpp.md。

  systemd.services.llama-cpp = {
    description = "llama-swap + llama.cpp (PrismML fork) — OpenAI-compatible, multi-model";

    # 自動起動 (2026-09-23〜)。以前は ollama との VRAM 競合で手動起動でした
    # (docs/decisions/2026-09-23-ollama-to-llama-cpp.md)。
    wantedBy = [ "multi-user.target" ];

    # nvidia-persistenced が上がっていればドライバは初期化済み。
    # laya-setup は requires ではなく wants: Laya の準備が失敗しても bonsai と
    # embedding は動くべきで、ルーター全体を道連れにしないため。
    after = [ "nvidia-persistenced.service" "network.target" "laya-setup.service" ];
    wants = [ "nvidia-persistenced.service" "laya-setup.service" ];

    environment = {
      # ★ PCI_BUS_ID から変えないこと ★ swapConfig の CUDA_VISIBLE_DEVICES は
      #   PCI バス順の番号です。2026-09-22 以前は FASTEST_FIRST で逆の注意書きが
      #   ありました (docs/decisions/2026-09-22-llama-swap-matrix.md)。
      #   子プロセスの llama-server に継承されます。
      CUDA_DEVICE_ORDER = "PCI_BUS_ID";
    };

    # クラッシュループの抑止。5 分のうち 3 回失敗したら諦めます。
    # ★ serviceConfig ではなくトップレベルに書くこと ★ StartLimit* は [Unit] の
    #   ディレクティブで、[Service] に書くと systemd が黙って捨て、OOM する 27B が
    #   10 秒ごとに永久に再起動し続けます。
    startLimitBurst = 3;
    startLimitIntervalSec = 300;

    serviceConfig = {
      # DynamicUser ではなく seita 本人。モデルが seita のホーム配下にあるため
      # (modules/fukurou.nix と同じ理由)。
      User = m.userName;
      Group = "users";
      WorkingDirectory = workDir;

      # --watch-config は付けない。設定は nix store 上の読み取り専用ファイルで、
      # 変更は rebuild → ExecStart の store パス変化 → 再起動、で反映されます。
      ExecStart = lib.concatStringsSep " " [
        "${pkgs.unstable.llama-swap}/bin/llama-swap"
        "--config ${swapConfig}"
        "--listen 127.0.0.1:${toString port}"
      ];

      Restart = "on-failure";
      RestartSec = 10;
    };
  };

  # laya-setup: [laya] の venv と重みを用意する冪等な oneshot ユニット。
  # 重みはここで取得し、実行時は HF_HUB_OFFLINE=1 で閉じます (初回に 647 MB を
  # 落とすと healthCheckTimeout を食い潰すため)。初回は torch の wheel 約 2.5 GB で
  # 数分かかります: journalctl -u laya-setup -f
  systemd.services.laya-setup = {
    description = "Laya venv + checkpoint setup (for llama-swap's [laya])";
    wantedBy = [ "multi-user.target" ];

    # pip も HuggingFace も外に出ます。network.target では「設定済み」を
    # 保証しないので online のほうを待ちます。
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];

    environment = {
      HF_HOME = layaHfHome;
      LD_LIBRARY_PATH = layaLdPath;
    };

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      User = m.userName;
      Group = "users";

      # 初回は torch の DL とインストールで数分かかります。既定の
      # 90 秒では足りません。
      TimeoutStartSec = "30min";
    };

    script = ''
      set -euo pipefail

      mkdir -p ${layaDir} ${layaHfHome}

      if [ ! -x ${layaVenv}/bin/python ]; then
        ${pkgs.uv}/bin/uv venv --python ${pkgs.python3}/bin/python3 ${layaVenv}
      fi

      # torch は PyTorch 公式の cu121 インデックスから。PyPI の torch は
      # CUDA 版ではないので、--index-url を外さないこと。
      ${pkgs.uv}/bin/uv pip install --python ${layaVenv}/bin/python \
        --index-url https://download.pytorch.org/whl/cu121 \
        "torch==${layaTorchVersion}"

      # laya 本体 (transformers 等はこれが引きます) は通常の PyPI から。
      ${pkgs.uv}/bin/uv pip install --python ${layaVenv}/bin/python \
        "laya==${layaVersion}"

      # 重みの事前取得。CPU でロードするので VRAM は使いません。ここで
      # 落としておけば、実行時は HF_HUB_OFFLINE=1 で足ります。
      # 同時に「venv が実際に import できるか」の検証も兼ねています。
      ${layaVenv}/bin/python -c '
import laya
laya.load("${layaRepo}", subfolder="${layaSubfolder}", device="cpu")
print("laya checkpoint ready")
'
    '';
  };
}
