{ config, lib, pkgs, ... }:

##############################################################################
# llama.cpp (PrismML fork) behind llama-swap, as a local LLM router.
# OpenAI-compatible API on 127.0.0.1:8888 (8080 is Open WebUI).
#
# Docs (history, measurements, caller-facing notes live there, not in comments):
#   docs/services/llama-cpp.md    overview, model list, caller-facing notes
#   docs/gpu-vram-budget.md       GPU mapping and measured VRAM breakdown
#   docs/runbooks/llama-cpp.md    fork updates, GPU swap, other procedures
#   docs/decisions/2026-09-2*-*   build method, llama-swap/matrix, Laya, migration from ollama
#
# When you change this file, update the docs above in the same commit.
##############################################################################

let
  m = import ../machine.nix;

  port = 8888;

  # Working directory for models and the router. A checkout of bonsai-workspaces.
  # Why models aren't on a disko dataset: docs/services/llama-cpp.md.
  workDir = "/home/${m.userName}/bonsai-workspaces";
  modelsDir = "${workDir}/models";

  ##########################################################################
  # Laya (a PyTorch decision model) — not llama.cpp, but colocated here so the
  # 1660 SUPER's VRAM is managed by the matrix in one place. Why it runs from
  # a pip venv: docs/decisions/2026-09-23-laya-in-llama-swap.md.
  ##########################################################################
  layaDir = "${workDir}/laya";
  layaVenv = "${layaDir}/venv";
  layaHfHome = "${layaDir}/hf";
  layaRepo = "convaiinnovations/laya";
  layaSubfolder = "multilingual"; # 322M, mmBERT-base, 1024 ctx, for Japanese

  # Pinned to the combination measured to work (2026-09-23). torch is the cu121 wheel.
  layaTorchVersion = "2.5.1";
  layaVersion = "0.3.6";

  # Three things pip's torch wheel needs to run on NixOS: libstdc++ (stdenv.cc.cc),
  # zlib, and libcuda.so's location /run/opengl-driver/lib (missing any one of
  # them fails, measured).
  layaLdPath = lib.makeLibraryPath [ pkgs.stdenv.cc.cc pkgs.zlib ] + ":/run/opengl-driver/lib";

  # Laya's HTTP wrapper (standard library only).
  # ** Do not change the load order "load on CPU -> half() -> GPU" ** loading the
  #   fp32 weights onto the GPU OOMs the 1660 SUPER (measured; see the Laya decision record in docs).
  layaServer = pkgs.writeText "laya-server.py" ''
    """Minimal HTTP wrapper around the laya decision model, for llama-swap.

    Generated by modules/llama-cpp.nix -- do not edit in place.

    Endpoints:
      GET  /health   -> 200 once the model is loaded (llama-swap checkEndpoint)
      POST /decide   -> {"state": ..., "questions": {...}} -> laya's answer
    """
    import argparse
    import json
    import sys
    import traceback
    from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

    import torch
    import laya

    REPO = "${layaRepo}"
    SUBFOLDER = "${layaSubfolder}"

    agent = None


    def load_agent():
        """Load on CPU, cast to fp16, then move to the GPU.

        The order matters: the fp32 weights (~1.3 GiB) do not fit next to the
        embedding server on the 1660 SUPER, so they must never touch the card.
        """
        global agent
        a = laya.load(REPO, subfolder=SUBFOLDER, device="cpu")
        if torch.cuda.is_available():
            a.model.half()
            a.model.to("cuda").eval()
            a.device = torch.device("cuda")
            a.dtype = torch.float16
            torch.cuda.empty_cache()
            print(
                "[laya-server] loaded fp16 on %s" % torch.cuda.get_device_name(0),
                flush=True,
            )
        else:
            # Keep serving rather than dying: a slower answer beats a dead
            # branch in n8n. ~112 ms vs ~71 ms for a short input (measured).
            print(
                "[laya-server] WARNING: CUDA unavailable, running on CPU (slower)",
                flush=True,
            )
        agent = a


    class Handler(BaseHTTPRequestHandler):
        def _send(self, code, payload):
            body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            if self.path.rstrip("/") in ("/health", ""):
                ready = agent is not None
                self._send(200 if ready else 503, {"status": "ok" if ready else "loading"})
            else:
                self._send(404, {"error": "not found: %s" % self.path})

        def do_POST(self):
            if self.path.rstrip("/") != "/decide":
                self._send(404, {"error": "not found: %s" % self.path})
                return
            try:
                n = int(self.headers.get("Content-Length") or 0)
                req = json.loads(self.rfile.read(n) or b"{}")
                state = req["state"]
                questions = req["questions"]
            except Exception as e:
                self._send(400, {"error": "bad request: %s" % e})
                return
            try:
                self._send(200, agent.system_one(state, questions))
            except Exception as e:
                traceback.print_exc()
                self._send(500, {"error": str(e)})

        def log_message(self, fmt, *args):
            # journald already timestamps; keep one line per request.
            sys.stderr.write("[laya-server] " + (fmt % args) + "\n")


    def main():
        ap = argparse.ArgumentParser()
        ap.add_argument("--port", type=int, required=True)
        ap.add_argument("--host", default="127.0.0.1")
        args = ap.parse_args()

        load_agent()
        srv = ThreadingHTTPServer((args.host, args.port), Handler)
        print("[laya-server] listening on %s:%d" % (args.host, args.port), flush=True)
        srv.serve_forever()


    if __name__ == "__main__":
        main()
  '';

  ##########################################################################
  # Source of the PrismML fork. rev / hash must match
  # ~/bonsai-workspaces/flake.lock, which is the source of truth (update
  # procedure: docs/runbooks/llama-cpp.md). Why the fork, and why not a
  # flake input: docs/decisions/2026-09-21-llama-cpp-prism-build.md.
  ##########################################################################
  prismRev = "9a9394a895b96003ca842a6041cb28ac49a108f7";
  prismHash = "sha256-KDecY+v9S/193mLGse5EsJPugZR1wxWzOlOU7GuMd5Y=";

  prismSrc = pkgs.fetchFromGitHub {
    owner = "PrismML-Eng";
    repo = "llama.cpp";
    rev = prismRev;
    hash = prismHash;
  };

  # Swap nixpkgs' llama-cpp for the fork's source. cudaSupport is named here,
  # not set nixpkgs-wide (see CLAUDE.md's cudaSupport section).
  # patches = [] because nixpkgs' patches assume upstream line numbers and
  # don't apply to the fork.
  llamaCppPrism =
    (pkgs.unstable.llama-cpp.override { cudaSupport = true; }).overrideAttrs
      (old: {
        pname = "llama-cpp-prism";
        version = builtins.substring 0 7 prismRev;
        src = prismSrc;
        patches = [ ];
        doCheck = false;

        # Only this host's 2 cards: 75 = GTX 1660 SUPER / 86 = RTX 3060 Ti.
        # nixpkgs' default of 9 architectures makes the first build several
        # times longer.
        # ** Update this when you swap a GPU ** a mismatched SM fails with a CUDA error at startup.
        cmakeFlags =
          (builtins.filter
            (f: !(lib.hasPrefix "-DCMAKE_CUDA_ARCHITECTURES" f))
            old.cmakeFlags)
          ++ [ "-DCMAKE_CUDA_ARCHITECTURES:STRING=75;86" ];
      });

  ##########################################################################
  # llama-swap's config YAML. Each model starts llama-server as a child
  # process, and the combinations that can coexist are written as matrix
  # sets (why not the fork's own router:
  #  docs/decisions/2026-09-22-llama-swap-matrix.md).
  #
  # GPUs are assigned per model via CUDA_VISIBLE_DEVICES. Numbers follow PCI bus order:
  #   "1" = RTX 3060 Ti (bonsai family)   "0" = GTX 1660 SUPER (embedding / laya)
  # All numbers (context ceilings, VRAM breakdown) are measured; see
  # docs/gpu-vram-budget.md. ** Do not raise a number without measuring it **
  ##########################################################################
  bonsaiModel = "${modelsDir}/Ternary-Bonsai-2-27B-gguf/Ternary-Bonsai-2-27B-PTQ1_0.gguf";

  swapConfig = pkgs.writeText "llama-swap.yaml" ''
    # This file is generated by Nix. Do not edit it directly
    # (modules/llama-cpp.nix is the source of truth).

    # Starting port number for the child llama-server processes. Chosen to
    # avoid 8888 (llama-swap itself), 8080 (Open WebUI), and 5678 (n8n).
    startPort: 18900

    # Loading the 27B takes a while. The default of 500s is enough, but made explicit.
    healthCheckTimeout: 500
    logLevel: info

    # 0 = no automatic unload. Eviction is left to the matrix.
    globalTTL: 0

    macros:
      # PORT is a variable llama-swap assigns per model, not Nix interpolation
      # (escaped with a doubled single quote).
      "server": "${llamaCppPrism}/bin/llama-server --port ''${PORT}"

    models:
      # Bonsai 2 / PTQ1_0, alone on the 3060 Ti.
      # -c 81920 is the measured ceiling with KV q4_0 (90112 fails). Do not raise it.
      # Do not drop -np 1 (the default of 4 slots OOMs the 27B).
      "bonsai":
        name: "Bonsai 2 27B (80K)"
        env:
          - "CUDA_VISIBLE_DEVICES=1"
        cmd: |
          ''${server}
          --model ${bonsaiModel}
          --jinja
          -np 1
          -ngl 99
          -c 81920
          --cache-type-k q4_0
          --cache-type-v q4_0
          --temp 0.5
          --top-p 0.85
          --top-k 20

      # Same weights + a vision projector (+600 MB). Context drops to 8192 accordingly.
      "bonsai-vision":
        name: "Bonsai 2 27B (vision)"
        env:
          - "CUDA_VISIBLE_DEVICES=1"
        cmd: |
          ''${server}
          --model ${bonsaiModel}
          --mmproj ${modelsDir}/Ternary-Bonsai-2-27B-gguf/Ternary-Bonsai-2-27B-mmproj-Q8_0.gguf
          --jinja
          -np 1
          -ngl 99
          -c 8192
          --cache-type-k q8_0
          --cache-type-v q8_0
          --temp 0.5
          --top-p 0.85
          --top-k 20

      # Everything below runs on the 1660 SUPER. Not interfering with bonsai
      # comes down to hiding the 3060 Ti entirely via CUDA_VISIBLE_DEVICES=0
      # (-ngl alone isn't enough). This card only has a few hundred MiB free.
      # Always measure before adding anything.

      # Qwen3-Embedding-4B, 2560 dims (measured on this router). Used by OpenViking.
      "embedding":
        name: "Qwen3 Embedding 4B"
        env:
          - "CUDA_VISIBLE_DEVICES=0"
        cmd: |
          ''${server}
          --model ${modelsDir}/Qwen3-Embedding-4B-GGUF/Qwen3-Embedding-4B-Q4_K_M.gguf
          --embeddings
          --pooling last
          -ngl 99
          -c 8192

      # Laya multilingual (322M) — decision model (PyTorch) for n8n's flow branching.
      # Called via POST /upstream/laya/decide (docs/services/llama-cpp.md).
      # concurrencyLimit 1: only one model on the GPU; running requests in
      # parallel would only raise the VRAM peak, so serialize them.
      "laya":
        name: "Laya multilingual (decision)"
        checkEndpoint: /health
        concurrencyLimit: 1
        env:
          - "CUDA_VISIBLE_DEVICES=0"
          - "LD_LIBRARY_PATH=${layaLdPath}"
          - "HF_HOME=${layaHfHome}"
          # Do not let it reach the network at runtime. laya-setup.service
          # fetches the weights ahead of time; if that failed, this fails
          # immediately instead.
          - "HF_HUB_OFFLINE=1"
        cmd: |
          ${layaVenv}/bin/python ${layaServer} --port ''${PORT}

    # Combinations allowed to run at the same time. Subsets of a set are also
    # allowed, so one is enough. bonsai and bonsai-vision are separate
    # branches because they occupy the same 3060 Ti.
    routing:
      router:
        use: matrix
        settings:
          matrix:
            evict_costs:
              # 27B + 80K KV. Loading is expensive, so keep it resident longest.
              bonsai: 50
              bonsai-vision: 50
              # Embedding is light and on a different card, no reason to evict it.
              embedding: 1
              # Keep it longer than embedding because it blocks n8n's branching
              # synchronously; cheaper to evict than bonsai.
              laya: 30
            sets:
              generation: "(bonsai | bonsai-vision) & embedding & laya"
  '';
in
{
  # Deliberately not in environment.systemPackages: it ships a binary named
  # `llama`, generic enough to collide on PATH. How to use it interactively:
  # docs/services/llama-cpp.md.

  systemd.services.llama-cpp = {
    description = "llama-swap + llama.cpp (PrismML fork) — OpenAI-compatible, multi-model";

    # Auto-starts (2026-09-23~). Was manual-start before, due to VRAM
    # contention with ollama (docs/decisions/2026-09-23-ollama-to-llama-cpp.md).
    wantedBy = [ "multi-user.target" ];

    # If nvidia-persistenced is up, the driver is already initialized.
    # laya-setup is a `wants`, not `requires`: bonsai and embedding should
    # keep working even if Laya's setup fails, so it shouldn't take the
    # whole router down with it.
    after = [ "nvidia-persistenced.service" "network.target" "laya-setup.service" ];
    wants = [ "nvidia-persistenced.service" "laya-setup.service" ];

    environment = {
      # ** Do not change from PCI_BUS_ID ** swapConfig's CUDA_VISIBLE_DEVICES
      #   numbers follow PCI bus order. Before 2026-09-22 this was
      #   FASTEST_FIRST with the opposite warning
      #   (docs/decisions/2026-09-22-llama-swap-matrix.md).
      #   Inherited by the child llama-server processes.
      CUDA_DEVICE_ORDER = "PCI_BUS_ID";
    };

    # Suppress crash loops: give up after 3 failures in 5 minutes.
    # ** Keep these top-level, not inside serviceConfig ** StartLimit* are
    #   [Unit] directives; putting them under [Service] makes systemd
    #   silently drop them, so an OOMing 27B restarts forever every 10s.
    startLimitBurst = 3;
    startLimitIntervalSec = 300;

    serviceConfig = {
      # Runs as seita, not DynamicUser, because the models live under
      # seita's home (same reason as modules/fukurou.nix).
      User = m.userName;
      Group = "users";
      WorkingDirectory = workDir;

      # No --watch-config: the config is a read-only file in the nix store;
      # changes only take effect via rebuild -> ExecStart's store path
      # changes -> restart.
      ExecStart = lib.concatStringsSep " " [
        "${pkgs.unstable.llama-swap}/bin/llama-swap"
        "--config ${swapConfig}"
        "--listen 127.0.0.1:${toString port}"
      ];

      Restart = "on-failure";
      RestartSec = 10;
    };
  };

  # laya-setup: an idempotent oneshot unit that prepares [laya]'s venv and weights.
  # Weights are fetched here and closed off at runtime with HF_HUB_OFFLINE=1
  # (fetching 647 MB on first request would eat up healthCheckTimeout). First
  # run takes a few minutes for the ~2.5 GB torch wheel: journalctl -u laya-setup -f
  systemd.services.laya-setup = {
    description = "Laya venv + checkpoint setup (for llama-swap's [laya])";
    wantedBy = [ "multi-user.target" ];

    # Both pip and HuggingFace reach out to the network. network.target
    # doesn't guarantee "configured", so wait for online instead.
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];

    environment = {
      HF_HOME = layaHfHome;
      LD_LIBRARY_PATH = layaLdPath;
    };

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      User = m.userName;
      Group = "users";

      # First run takes a few minutes to download and install torch. The
      # default 90s isn't enough.
      TimeoutStartSec = "30min";
    };

    script = ''
      set -euo pipefail

      mkdir -p ${layaDir} ${layaHfHome}

      if [ ! -x ${layaVenv}/bin/python ]; then
        ${pkgs.uv}/bin/uv venv --python ${pkgs.python3}/bin/python3 ${layaVenv}
      fi

      # torch comes from PyTorch's own cu121 index. PyPI's torch isn't the
      # CUDA build, so don't drop --index-url.
      ${pkgs.uv}/bin/uv pip install --python ${layaVenv}/bin/python \
        --index-url https://download.pytorch.org/whl/cu121 \
        "torch==${layaTorchVersion}"

      # laya itself (pulls in transformers etc.) comes from regular PyPI.
      ${pkgs.uv}/bin/uv pip install --python ${layaVenv}/bin/python \
        "laya==${layaVersion}"

      # Pre-fetch the weights. Loaded on CPU, so no VRAM is used. Fetching
      # here means HF_HUB_OFFLINE=1 is enough at runtime. This also doubles
      # as a check that the venv can actually import the package.
      ${layaVenv}/bin/python -c '
import laya
laya.load("${layaRepo}", subfolder="${layaSubfolder}", device="cpu")
print("laya checkpoint ready")
'
    '';
  };
}
