# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_mem" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "bcachefs" ];

  # local-lvm:vm-106-disk1
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/91bfeff1-bffd-465e-981c-14ef65748ffa";
      fsType = "ext4";
    };

  # local-lvm:vm-106-disk1
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D074-78CC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # local-lvm:vm-106-disk3
  # fileSystems."/home" =
  #   #{ device = "/dev/disk/by-uuid/542dc3f6-b40f-4264-b624-6f25699d9322";
  #   { device = "/dev/disk/by-uuid/113f020f-b091-4d0d-96fe-93d3570267f8";
  #     fsType = "ext4";
  #   };

  # local-lvm:vm-106-disk2
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/55584c05-d735-41e8-b638-62a9926e9b25";
      fsType = "ext4";
    };

  # hdd-thin:vm-106-disk2
  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/d2944180-59d7-4f3a-8241-0c892785b316 ";
      fsType = "ext4";
    };

  # local-lvm:vm-106-disk4
  # hdd-thin:vm-106-disk1
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5c6723e2-4bc6-4f71-a5a7-41cf4e402450";
      fsType = "bcachefs";
      options = [
        "foreground_target=ssd" 
        "promote_target=ssd"
        "metadata_target=ssd"
        "background_target=hdd"
        "background_compression=zstd:3"
      ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
