{
 "title": "cgroup 別リソース (systemd ユニット / podman スライス)",
 "description": "cAdvisor は podman のコンテナ名を取れない (name ラベルが付かない) ため、cgroup パス (id) 単位で見ます。Minecraft コンテナは /minecraft.slice、その他の podman コンテナは /machine.slice、常駐サービスは /system.slice/<unit> です。",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "cgroup",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",id=~\"$container\"}[5m])) by (id) *100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$host\",id=~\"$container\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$host\",id=~\"$container\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "cgroup 一覧 (稼働日数)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"$host\",id=~\"$container\"})/86400",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}